//go:build !darwin
// +build !darwin

package gomtl

import "unsafe"

// CommandBuffer is a container that stores encoded commands
// that are committed to and executed by the GPU.
//
// Reference: https://developer.apple.com/documentation/metal/mtlcommandbuffer
type CommandBuffer struct {
	commandBuffer unsafe.Pointer
}

// Commit submits the command buffer to run on the GPU.
//
// Reference: https://developer.apple.com/documentation/metal/mtlcommandbuffer/1443003-commit
func (cb CommandBuffer) Commit() {
	panic("gomtl: Metal is only supported on macOS")
}

// WaitUntilCompleted waits for the execution of this command buffer to complete.
//
// Reference: https://developer.apple.com/documentation/metal/mtlcommandbuffer/1443039-waituntilcompleted
func (cb CommandBuffer) WaitUntilCompleted() {
	panic("gomtl: Metal is only supported on macOS")
}

// Drawable is a displayable resource that can be rendered or written to.
//
// Reference: https://developer.apple.com/documentation/metal/mtldrawable
type Drawable interface {
	// Drawable returns the underlying id<MTLDrawable> pointer.
	Drawable() uintptr
}

// PresentDrawable registers a drawable presentation to occur as soon as possible.
//
// Reference: https://developer.apple.com/documentation/metal/mtlcommandbuffer/1443029-presentdrawable
func (cb CommandBuffer) PresentDrawable(d Drawable) {
	panic("gomtl: Metal is only supported on macOS")
}

func (cb CommandBuffer) ComputeCommandEncoder() ComputeCommandEncoder {
	panic("gomtl: Metal is only supported on macOS")
}

// RenderPassDescriptor describes a group of render targets that serve as
// the output destination for pixels generated by a render pass.
//
// Reference: https://developer.apple.com/documentation/metal/mtlrenderpassdescriptor.
type RenderPassDescriptor struct {
	// ColorAttachments is array of state information for attachments that store color data.
	ColorAttachments [1]RenderPassColorAttachmentDescriptor
}

// RenderPassColorAttachmentDescriptor describes a color render target that serves
// as the output destination for color pixels generated by a render pass.
//
// Reference: https://developer.apple.com/documentation/metal/mtlrenderpasscolorattachmentdescriptor.
type RenderPassColorAttachmentDescriptor struct {
	RenderPassAttachmentDescriptor
	ClearColor ClearColor
}

// RenderPassAttachmentDescriptor describes a render target that serves
// as the output destination for pixels generated by a render pass.
//
// Reference: https://developer.apple.com/documentation/metal/mtlrenderpassattachmentdescriptor.
type RenderPassAttachmentDescriptor struct {
	LoadAction  LoadAction
	StoreAction StoreAction
	Texture     Texture
}

// RenderCommandEncoderWithDescriptor creates a render command encoder from the provided render pass descriptor.
// The render command encoder is used to encode commands that draw graphics with a GPU.
//
// Reference: https://developer.apple.com/documentation/metal/mtlcommandbuffer/1442999-rendercommandencoderwithdescript
func (cb CommandBuffer) RenderCommandEncoderWithDescriptor(rpd RenderPassDescriptor) RenderCommandEncoder {
	panic("gomtl: Metal is only supported on macOS")
}

// BlitCommandEncoder creates a blit command encoder.
// The blit command encoder is used to encode commands for quickly copying data between GPU resources, such as buffers and textures.
//
// Reference: https://developer.apple.com/documentation/metal/mtlcommandbuffer/1443001-blitcommandencoder
func (cb CommandBuffer) BlitCommandEncoder() BlitCommandEncoder {
	panic("gomtl: Metal is only supported on macOS")
}
